### ISSUE TITLE
Playing audio in a loop throws TaskCancelation errors

### ISSUE THREAD

**Issue by jandillmann** [jkeen/ember-stereo#25]
I'm using ember-stereo 4.3.0 to play a short audio clip in a loop like this:
```javascript
import Component from "@glimmer/component";
import { inject as service } from "@ember/service";
import { action } from "@ember/object";

export default class AlertComponent extends Component {
  @service stereo;

  @action
  startAlertSound() {
    if (!this.stereo.isPlaying) {
      this.stereo.on("audio-ended", () => this.stereo.play(["/assets/alert.mp3", "/assets/alert.ogg"]));
      this.stereo.play(["/assets/alert.mp3", "/assets/alert.ogg"]);
    }
  }

  @action
  stopAlertSound() {
    if (this.stereo.isPlaying) {
      this.stereo.pause();
      this.stereo.rewind(this.stereo.position);
    }
  }
}
```

This worked fine until updating the application to Ember 4.4, now the browser console shows this error every time the alert sound is played:

```
TaskCancelation: TaskInstance 'durationWorkaroundTask' was canceled because it belongs to a 'restartable' Task that was .perform()ed again. For more information, see: http://ember-concurrency.com/docs/task-cancelation-help
    at TaskInstanceExecutor.finalizeWithCancel (http://localhost:4201/assets/vendor.js:144270:19)
    at TaskInstanceExecutor.finalize (http://localhost:4201/assets/vendor.js:144252:21)
    at TaskInstanceExecutor.handleResolvedReturnedValue (http://localhost:4201/assets/vendor.js:144099:16)
    at TaskInstanceExecutor.proceedSync (http://localhost:4201/assets/vendor.js:144032:14)
    at http://localhost:4201/assets/vendor.js:144024:33
    at invoke (http://localhost:4201/assets/vendor.js:62317:16)
    at Queue.flush (http://localhost:4201/assets/vendor.js:62235:13)
    at DeferredActionQueues.flush (http://localhost:4201/assets/vendor.js:62389:21)
    at Backburner._end (http://localhost:4201/assets/vendor.js:62817:34)
    at Backburner.end (http://localhost:4201/assets/vendor.js:62620:12)
(anonymous) @ native-audio.js:231
invokeCallback @ rsvp.js:434
publish @ rsvp.js:420
publishRejection @ rsvp.js:369
(anonymous) @ rsvp.js:17
invoke @ backburner.js:270
flush @ backburner.js:188
flush @ backburner.js:342
_end @ backburner.js:770
end @ backburner.js:573
_run @ backburner.js:814
run @ backburner.js:608
run @ index.js:72
(anonymous) @ native-audio.js:71
```

The audio is still playing in a loop, but what can I do differently to prevent this error from showing in the browser console?

**Comment by jkeen** [comment]
@jandillmann I just pushed a fix so that error wouldn't be logged unless it errored for a reason that wasn't simply a task cancellation. Not sure why 4.4 brought that error out but the new patch version that's about to get released once tests pass will fix it for ya.
