### ISSUE TITLE
Support for Ember 4 ?

### ISSUE THREAD

**Issue by chrism** [jkeen/ember-stereo#8]
Hi,

Thought I'd give this project a spin to play some audio as the approach seems great.

After adding it to my Ember 4.2 project with

```
ember install ember-stereo
```

Then trying a basic play snippet in the application template, like

```hbs
  {{#let '/mp3/576851252.mp3' as |url|}}
    <button type='button' {{on 'click' (toggle-play-sound url)}}>Play</button>
  {{/let}}
```

I'm getting some errors... one is just a deprecation

```
deprecate.js:125 DEPRECATION: As of Ember 4.0.0, owner.inject no longer injects values into resolved instances, and calling the method has been deprecated. Since this method no longer does anything, it is fully safe to remove this injection. As an alternative to this API, you can refactor to explicitly inject `options` on `service:stereo`, or look it up directly using the `getOwner` API. [deprecation id: remove-owner-inject] See https://deprecations.emberjs.com/v4.x#toc_implicit-injections for more details.
```

The others are more serious

```
Error occurred:

- While rendering:
  -top-level
    application

execute @ runtime.js:5952
(anonymous) @ runtime.js:6038
runInTrackingTransaction @ validator.js:151
sync @ runtime.js:6038
(anonymous) @ index.js:5923
(anonymous) @ index.js:5892
(anonymous) @ index.js:6240
inTransaction @ runtime.js:4906
_renderRoots @ index.js:6220
_renderRootsTransaction @ index.js:6272
_renderRoot @ index.js:6207
_appendDefinition @ index.js:6114
appendOutletView @ index.js:6096
invoke @ backburner.js:340
flush @ backburner.js:229
flush @ backburner.js:426
_end @ backburner.js:958
end @ backburner.js:708
_run @ backburner.js:1013
run @ backburner.js:752
run @ index.js:116
callback @ application.js:426
util.js:61 
```

&

```
Uncaught ReferenceError: Ember is not defined
    at Module.callback (util.js:61:1)
    at Module.exports (loader.js:106:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
```

The Play button doesn't display...

So I was just wondering if this is a bug, or if not whether you have plans to support Ember 4.2 ?

Thanks!

**Comment by jkeen** [comment]
First off sorry for the delay here, somehow I missed this notification entirely. 😳

I want to support Ember 4, but the upgrade path has been bumpier than desired and I ran into all sorts of embroider-related errors last time I tried. I'm gonna give it another try this afternoon and see how it looks now that hopefully some upstream issues have been resolved

**Comment by chrism** [comment]
Hey, don't worry about it – I know how it is 😊

Good luck with the upgrade, would still be interested in giving it a try if you manage to get it working!

**Comment by jkeen** [comment]
@chrism Ember 4 compatibility just landed thanks to @fusion2004

**Comment by chrism** [comment]
Nice one!

Thanks for letting me know @jkeen & thanks too @fusion2004.
